'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pagina_principal

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''ResourcePlaceHolder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResourcePlaceHolder1 As Global.Ext.Net.ResourcePlaceHolder

    '''<summary>
    '''frmPanelPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmPanelPrincipal As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ResourceManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResourceManager1 As Global.Ext.Net.ResourceManager

    '''<summary>
    '''Viewport1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Viewport1 As Global.Ext.Net.Viewport

    '''<summary>
    '''pnlToolbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlToolbar As Global.Ext.Net.Panel

    '''<summary>
    '''Toolbar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Toolbar1 As Global.Ext.Net.Toolbar

    '''<summary>
    '''DisplayField12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DisplayField12 As Global.Ext.Net.Panel

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''BtnSesionCnfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSesionCnfg As Global.Ext.Net.Button

    '''<summary>
    '''Menu1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu1 As Global.Ext.Net.Menu

    '''<summary>
    '''mnuPerfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuPerfil As Global.Ext.Net.MenuItem

    '''<summary>
    '''mnuchangePass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuchangePass As Global.Ext.Net.MenuItem

    '''<summary>
    '''mnulogOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnulogOut As Global.Ext.Net.MenuItem

    '''<summary>
    '''tabPanelPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabPanelPrincipal As Global.Ext.Net.TabPanel

    '''<summary>
    '''PanelInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelInfo As Global.Ext.Net.Panel

    '''<summary>
    '''pnlOeste control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOeste As Global.Ext.Net.Panel

    '''<summary>
<<<<<<< HEAD
    '''mpCatalogos1 control.
=======
    '''mpCatalogos control.
>>>>>>> origin/master
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpCatalogos1 As Global.Ext.Net.MenuPanel

    '''<summary>
    '''miTipoLugar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents miTipoLugar As Global.Ext.Net.MenuItem

    '''<summary>
<<<<<<< HEAD
    '''mpCompras2 control.
=======
<<<<<<< HEAD
    '''miProveedores control.
=======
    '''Control MenuPanel1.
>>>>>>> origin/master
>>>>>>> origin/master
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpCompras2 As Global.Ext.Net.MenuPanel

    '''<summary>
<<<<<<< HEAD
    '''MenuItem1 control.
=======
<<<<<<< HEAD
    '''miContabilidad control.
=======
    '''Control MenuItem1.
>>>>>>> origin/master
>>>>>>> origin/master
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuItem1 As Global.Ext.Net.MenuItem

    '''<summary>
<<<<<<< HEAD
    '''mpVentas3 control.
=======
<<<<<<< HEAD
    '''miEmpleados control.
=======
    '''Control MenuPanel2.
>>>>>>> origin/master
>>>>>>> origin/master
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpVentas3 As Global.Ext.Net.MenuPanel

    '''<summary>
<<<<<<< HEAD
    '''MenuItem2 control.
=======
<<<<<<< HEAD
    '''mpContabilidad control.
=======
    '''Control MenuItem2.
>>>>>>> origin/master
>>>>>>> origin/master
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
<<<<<<< HEAD
    Protected WithEvents mpContabilidad As Global.Ext.Net.MenuPanel

    '''<summary>
    '''mDiario control.
=======
    Protected WithEvents MenuItem2 As Global.Ext.Net.MenuItem

    '''<summary>
<<<<<<< HEAD
    '''mpContabilidad4 control.
=======
    '''Control MenuPanel3.
>>>>>>> origin/master
>>>>>>> origin/master
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
<<<<<<< HEAD
    Protected WithEvents mpContabilidad4 As Global.Ext.Net.MenuPanel

    '''<summary>
    '''MenuItem6 control.
=======
<<<<<<< HEAD
    Protected WithEvents mDiario As Global.Ext.Net.MenuItem

    '''<summary>
    '''mBalance control.
=======
    Protected WithEvents MenuPanel3 As Global.Ext.Net.MenuPanel

    '''<summary>
    '''Control MenuItem3.
>>>>>>> origin/master
>>>>>>> origin/master
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
<<<<<<< HEAD
    Protected WithEvents MenuItem6 As Global.Ext.Net.MenuItem

    '''<summary>
    '''mpsCliente5 control.
=======
<<<<<<< HEAD
    Protected WithEvents mBalance As Global.Ext.Net.MenuItem

    '''<summary>
    '''mResultados control.
=======
    Protected WithEvents MenuItem3 As Global.Ext.Net.MenuItem

    '''<summary>
    '''Control MenuPanel4.
>>>>>>> origin/master
>>>>>>> origin/master
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
<<<<<<< HEAD
    Protected WithEvents mpsCliente5 As Global.Ext.Net.MenuPanel

    '''<summary>
    '''MenuItem7 control.
=======
<<<<<<< HEAD
    Protected WithEvents mResultados As Global.Ext.Net.MenuItem

    '''<summary>
    '''mpVentas control.
=======
    Protected WithEvents MenuPanel4 As Global.Ext.Net.MenuPanel

    '''<summary>
    '''Control MenuItem4.
>>>>>>> origin/master
>>>>>>> origin/master
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
<<<<<<< HEAD
    '''</remarks>
    Protected WithEvents MenuItem7 As Global.Ext.Net.MenuItem
=======
    '''</remarks>
<<<<<<< HEAD
    Protected WithEvents mpVentas As Global.Ext.Net.MenuPanel

    '''<summary>
    '''miVentas1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents miVentas1 As Global.Ext.Net.MenuItem
=======
    Protected WithEvents MenuItem4 As Global.Ext.Net.MenuItem
>>>>>>> origin/master

    '''<summary>
    '''mpAdministracion6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpAdministracion6 As Global.Ext.Net.MenuPanel

    '''<summary>
    '''MenuItem8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
<<<<<<< HEAD
    Protected WithEvents MenuItem8 As Global.Ext.Net.MenuItem
=======
    Protected WithEvents MenuItem5 As Global.Ext.Net.MenuItem
>>>>>>> origin/master
>>>>>>> origin/master
End Class
